
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfybqimuaybnvmgefhhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmeWJxaW11YXlibnZtZ2VmaGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NTAxNjIsImV4cCI6MjA1NTUyNjE2Mn0.HD8YVQL0q3xN1ww98cTgqGxOww7cI6pTBMRi9t5BNzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);
